// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using shoe_project_server.Data;

#nullable disable

namespace shoe_project_server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240103094101_update-fr-key")]
    partial class updatefrkey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("shoe_project_server.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("UserRole")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("shoe_project_server.Models.Favourite", b =>
                {
                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.HasKey("userId", "productId");

                    b.ToTable("favourites");
                });

            modelBuilder.Entity("shoe_project_server.Models.Order", b =>
                {
                    b.Property<int>("orderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("customerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("customerPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("deliveryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("orderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("orderStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("orderId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("shoe_project_server.Models.Producer", b =>
                {
                    b.Property<int>("producerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("producerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("producerId");

                    b.ToTable("producers");
                });

            modelBuilder.Entity("shoe_project_server.Models.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ProductDescribe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("producerId")
                        .HasColumnType("int");

                    b.Property<string>("productImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("productPrice")
                        .HasColumnType("double");

                    b.HasKey("productId");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            productId = 1,
                            ProductDescribe = "Sự rạng rỡ vẫn tồn tại trong Nike Air Force 1 '07, phiên bản bóng rổ nguyên bản mang đến sự thay đổi mới mẻ về những gì bạn biết rõ nhất: lớp phủ được khâu bền, lớp hoàn thiện gọn gàng và lượng đèn flash hoàn hảo giúp bạn tỏa sáng.",
                            producerId = 1,
                            productImage = "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/b7d9211c-26e7-431a-ac24-b0540fb3c00f/air-force-1-07-shoes-WrLlWX.png",
                            productName = "Nike Air Force 1 '07",
                            productPrice = 2929000.0
                        },
                        new
                        {
                            productId = 2,
                            ProductDescribe = "Sự rạng rỡ vẫn tồn tại trong Nike Air Force 1 '07, phiên bản bóng rổ nguyên bản mang đến sự thay đổi mới mẻ về những gì bạn biết rõ nhất: lớp phủ được khâu bền, lớp hoàn thiện gọn gàng và lượng đèn flash hoàn hảo giúp bạn tỏa sáng.",
                            producerId = 1,
                            productImage = "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/c82501e4-317d-4cc4-bd10-e7c947ce31a0/gamma-force-shoes-CbTnH1.png",
                            productName = "Nike Gamma Force",
                            productPrice = 2649000.0
                        },
                        new
                        {
                            productId = 3,
                            ProductDescribe = "Lần trước, LeBron đã lật ngược kịch bản trận đấu đánh giày của mình mà chỉ có Nhà vua mới có thể làm được. Bản encore thậm chí còn hay hơn. Với các bộ phận Air Zoom và đệm mềm, LeBron XXI (còn được gọi là LeBron 21) mang đến cho bạn sự linh hoạt và sức mạnh mà không cần quá nhiều trọng lượng để làm bạn chậm lại. Lý tưởng cho các cuộc chạy vòng, đột phá nhanh và chạy đua lên xuống sân, chúng giúp bạn tiếp tục chơi ở đỉnh cao của trận đấu cho đến khi tiếng còi cuối cùng vang lên. Bạn đã sẵn sàng chơi chưa?",
                            producerId = 1,
                            productImage = "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/2b050e6a-4647-4647-babb-32b1fa8d33a6/lebron-xxi-tahitian-younger-older-basketball-shoes-Q0HDBH.png",
                            productName = "LeBron XXI 'Tahitian'",
                            productPrice = 4079000.0
                        },
                        new
                        {
                            productId = 4,
                            ProductDescribe = "Bạn đã bao giờ nhìn vào một quả trứng cá và nghĩ, \"Ồ, tuyệt quá!\"? Với những màu sắc được kết hợp từ thiên nhiên, chiếc AJ1 này tôn vinh mọi thứ ở ngoài trời. Tất nhiên, bạn vẫn có được tất cả các đặc điểm thiết kế cổ điển, như phần trên chắc chắn và đế Nike Air. Và nó đi kèm với một túi dây rút có thể tháo rời — đề phòng trường hợp bạn tìm thấy một quả đấu đặc biệt thú vị mà bạn muốn giữ lại.",
                            producerId = 1,
                            productImage = "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/08577b4f-c209-468f-a017-1b3eba9a90b7/air-jordan-1-low-se-older-shoes-HPgPbg.png",
                            productName = "Air Jordan 1 Low SE",
                            productPrice = 2809000.0
                        },
                        new
                        {
                            productId = 5,
                            ProductDescribe = "Bạn đã bao giờ nhìn vào một quả trứng cá và nghĩ, \"Ồ, tuyệt quá!\"? Với những màu sắc được kết hợp từ thiên nhiên, những cú đá này tôn vinh mọi thứ ở ngoài trời. Tất nhiên, bạn vẫn có được tất cả các đặc điểm thiết kế cổ điển, chẳng hạn như kết cấu phần trên và đế cốc chắc chắn. Và nó đi kèm với một túi dây rút có thể tháo rời — đề phòng trường hợp bạn tìm thấy một quả đấu đặc biệt thú vị để giữ.",
                            producerId = 1,
                            productImage = "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/06f07a18-b639-4297-9641-2a99f848368d/jordan-1-low-alt-se-younger-shoes-6ksx5c.png",
                            productName = "Jordan 1 Low Alt SE",
                            productPrice = 1789000.0
                        },
                        new
                        {
                            productId = 6,
                            ProductDescribe = "Bạn đã bao giờ nhìn vào một quả trứng cá và nghĩ, \"Ồ, tuyệt quá!\"? Với những màu sắc được kết hợp từ thiên nhiên, những cú đá này tôn vinh mọi thứ ở ngoài trời. Tất nhiên, bạn vẫn có được tất cả các đặc điểm thiết kế cổ điển, chẳng hạn như kết cấu phần trên và đế cốc chắc chắn. Và nó đi kèm với một túi dây rút có thể tháo rời — đề phòng trường hợp bạn tìm thấy một quả đấu đặc biệt thú vị để giữ.",
                            producerId = 2,
                            productImage = "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/a530b99a-cc0b-49ea-8082-db3e1e073910/air-force-1-older-shoes-lNjVW6.png",
                            productName = "Nike Air Force 1",
                            productPrice = 2809000.0
                        },
                        new
                        {
                            productId = 7,
                            ProductDescribe = "Bạn đã bao giờ nhìn vào một quả trứng cá và nghĩ, \"Ồ, tuyệt quá!\"? Với những màu sắc được kết hợp từ thiên nhiên, những cú đá này tôn vinh mọi thứ ở ngoài trời. Tất nhiên, bạn vẫn có được tất cả các đặc điểm thiết kế cổ điển, chẳng hạn như kết cấu phần trên và đế cốc chắc chắn. Và nó đi kèm với một túi dây rút có thể tháo rời — đề phòng trường hợp bạn tìm thấy một quả đấu đặc biệt thú vị để giữ.",
                            producerId = 2,
                            productImage = "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cc540e66-3b4e-4e64-a537-cf089a7ca84e/air-force-1-07-shoes-CMNWtG.png",
                            productName = "Nike Air Force 1'07",
                            productPrice = 3239000.0
                        },
                        new
                        {
                            productId = 8,
                            ProductDescribe = "Bạn đã bao giờ nhìn vào một quả trứng cá và nghĩ, \"Ồ, tuyệt quá!\"? Với những màu sắc được kết hợp từ thiên nhiên, những cú đá này tôn vinh mọi thứ ở ngoài trời. Tất nhiên, bạn vẫn có được tất cả các đặc điểm thiết kế cổ điển, chẳng hạn như kết cấu phần trên và đế cốc chắc chắn. Và nó đi kèm với một túi dây rút có thể tháo rời — đề phòng trường hợp bạn tìm thấy một quả đấu đặc biệt thú vị để giữ.",
                            producerId = 2,
                            productImage = "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/cc540e66-3b4e-4e64-a537-cf089a7ca84e/air-force-1-07-shoes-CMNWtG.png",
                            productName = "Air Jordan XXXVIII",
                            productPrice = 3959000.0
                        },
                        new
                        {
                            productId = 9,
                            ProductDescribe = "Bạn đã bao giờ nhìn vào một quả trứng cá và nghĩ, \"Ồ, tuyệt quá!\"? Với những màu sắc được kết hợp từ thiên nhiên, những cú đá này tôn vinh mọi thứ ở ngoài trời. Tất nhiên, bạn vẫn có được tất cả các đặc điểm thiết kế cổ điển, chẳng hạn như kết cấu phần trên và đế cốc chắc chắn. Và nó đi kèm với một túi dây rút có thể tháo rời — đề phòng trường hợp bạn tìm thấy một quả đấu đặc biệt thú vị để giữ.",
                            producerId = 2,
                            productImage = "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/bf877156-a080-457b-bc96-7d7c76378165/air-jordan-xxxviii-fiba-older-shoes-jsK87k.png",
                            productName = "Air Jordan XXXVIII 'FIBA'",
                            productPrice = 3959000.0
                        },
                        new
                        {
                            productId = 10,
                            ProductDescribe = "Bạn đã bao giờ nhìn vào một quả trứng cá và nghĩ, \"Ồ, tuyệt quá!\"? Với những màu sắc được kết hợp từ thiên nhiên, những cú đá này tôn vinh mọi thứ ở ngoài trời. Tất nhiên, bạn vẫn có được tất cả các đặc điểm thiết kế cổ điển, chẳng hạn như kết cấu phần trên và đế cốc chắc chắn. Và nó đi kèm với một túi dây rút có thể tháo rời — đề phòng trường hợp bạn tìm thấy một quả đấu đặc biệt thú vị để giữ.",
                            producerId = 2,
                            productImage = "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,u_126ab356-44d8-4a06-89b4-fcdcc8df0245,c_scale,fl_relative,w_1.0,h_1.0,fl_layer_apply/ae63e73a-f213-4734-8cf4-c57475e769e5/air-jordan-1-low-flyease-older-shoes-Pr8pJH.png",
                            productName = "Air Jordan 1 Low FlyEase",
                            productPrice = 2489649.0
                        },
                        new
                        {
                            productId = 11,
                            ProductDescribe = "Bạn đã bao giờ nhìn vào một quả trứng cá và nghĩ, \"Ồ, tuyệt quá!\"? Với những màu sắc được kết hợp từ thiên nhiên, những cú đá này tôn vinh mọi thứ ở ngoài trời. Tất nhiên, bạn vẫn có được tất cả các đặc điểm thiết kế cổ điển, chẳng hạn như kết cấu phần trên và đế cốc chắc chắn. Và nó đi kèm với một túi dây rút có thể tháo rời — đề phòng trường hợp bạn tìm thấy một quả đấu đặc biệt thú vị để giữ.",
                            producerId = 3,
                            productImage = "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/35cd473e-b388-4de0-83f5-8a8f3287eef6/dunk-low-retro-shoes-Zc0601.png",
                            productName = "Nike Dunk Low Retro Premium",
                            productPrice = 3519000.0
                        },
                        new
                        {
                            productId = 12,
                            ProductDescribe = "Hãy thắt dây giày và cảm nhận di sản từ đôi giày chạy bộ vô địch đã giúp định hình thập niên 90 này. Được các tổng thống sử dụng, được cách mạng hóa thông qua sự hợp tác và được tôn vinh nhờ các màu sắc hiếm có, đế ngoài Waffle, đệm Nike Air có thể nhìn thấy và hình ảnh ấn tượng đã giúp nó luôn tồn tại và hoạt động tốt.",
                            producerId = 3,
                            productImage = "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/ae178e75-38aa-4212-ba98-3f2d45b7ac13/air-max-90-shoes-0MB5rJ.png",
                            productName = "Nike Air Max 90",
                            productPrice = 3829000.0
                        },
                        new
                        {
                            productId = 13,
                            ProductDescribe = "Hãy thắt dây giày và cảm nhận di sản từ đôi giày chạy bộ vô địch đã giúp định hình thập niên 90 này. Được các tổng thống sử dụng, được cách mạng hóa thông qua sự hợp tác và được tôn vinh nhờ các màu sắc hiếm có, đế ngoài Waffle, đệm Nike Air có thể nhìn thấy và hình ảnh ấn tượng đã giúp nó luôn tồn tại và hoạt động tốt.",
                            producerId = 3,
                            productImage = "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/3251a6d3-13bd-4fc1-8874-272b554f44a1/go-flyease-easy-on-off-shoes-3svRCL.png",
                            productName = "Nike Go FlyEase",
                            productPrice = 3829000.0
                        },
                        new
                        {
                            productId = 14,
                            ProductDescribe = "Hãy thắt dây giày và cảm nhận di sản từ đôi giày chạy bộ vô địch đã giúp định hình thập niên 90 này. Được các tổng thống sử dụng, được cách mạng hóa thông qua sự hợp tác và được tôn vinh nhờ các màu sắc hiếm có, đế ngoài Waffle, đệm Nike Air có thể nhìn thấy và hình ảnh ấn tượng đã giúp nó luôn tồn tại và hoạt động tốt.",
                            producerId = 3,
                            productImage = "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/767687a0-142e-4d66-b437-998dee9a0a4f/nikecourt-royale-2-next-nature-shoes-RRcr20.png",
                            productName = "NikeCourt Royale 2 Next Nature",
                            productPrice = 1609000.0
                        },
                        new
                        {
                            productId = 15,
                            ProductDescribe = "Hãy thắt dây giày và cảm nhận di sản từ đôi giày chạy bộ vô địch đã giúp định hình thập niên 90 này. Được các tổng thống sử dụng, được cách mạng hóa thông qua sự hợp tác và được tôn vinh nhờ các màu sắc hiếm có, đế ngoài Waffle, đệm Nike Air có thể nhìn thấy và hình ảnh ấn tượng đã giúp nó luôn tồn tại và hoạt động tốt.",
                            producerId = 3,
                            productImage = "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/b14aba9a-f828-45d3-9607-b687b884aa7d/revolution-7-easyon-road-running-shoes-nNqdwt.png",
                            productName = "Nike Revolution 7 EasyOn",
                            productPrice = 1789000.0
                        });
                });

            modelBuilder.Entity("shoe_project_server.Models.ProductDetail", b =>
                {
                    b.Property<int>("productDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("productColor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("productSize")
                        .HasColumnType("int");

                    b.HasKey("productDetailId");

                    b.ToTable("productDetails");
                });

            modelBuilder.Entity("shoe_project_server.Models.ProductImage", b =>
                {
                    b.Property<int>("productImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("producId")
                        .HasColumnType("int");

                    b.Property<string>("productImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("productImageId");

                    b.ToTable("productImages");
                });

            modelBuilder.Entity("shoe_project_server.Models.PurchaseHistory", b =>
                {
                    b.Property<int>("orderId")
                        .HasColumnType("int");

                    b.Property<int>("userId")
                        .HasColumnType("int");

                    b.Property<int>("productId")
                        .HasColumnType("int");

                    b.Property<int>("productQuantity")
                        .HasColumnType("int");

                    b.HasKey("orderId", "userId");

                    b.HasIndex("productId");

                    b.ToTable("purchaseHistories");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("shoe_project_server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("shoe_project_server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("shoe_project_server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("shoe_project_server.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("shoe_project_server.Models.PurchaseHistory", b =>
                {
                    b.HasOne("shoe_project_server.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
